name = "rotas-overpass-proxy"
main = "src/index.ts"
compatibility_date = "2024-03-20"

routes = [
  { pattern = "api.rotas.cc/api/neighborhoods", zone_name = "rotas.cc" },
  { pattern = "api.rotas.cc/api/roads", zone_name = "rotas.cc" },
  { pattern = "api.rotas.cc/api/openapi.json", zone_name = "rotas.cc" },
  { pattern = "api.rotas.cc/proxy", zone_name = "rotas.cc" }
]

# Optional: Disable default subdomain or customize routes
# workers_dev = true
